version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: checklist_postgres
    restart: always
    environment:
      POSTGRES_USER: checklist_user
      POSTGRES_PASSWORD: checklist_pass
      POSTGRES_DB: checklist_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
